apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: symfony
spec:
  type: NodePort
  selector:
    app: symfony
    component: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 8080