apiVersion: apps/v1
kind: Deployment
metadata:
  name: race-timer-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: race-timer-api
  template:
    metadata:
      labels:
        app: race-timer-api
    spec:
      containers:
        - name: race-timer-api
          image: stjepan11/race-timer-api:latest
          ports:
            - containerPort: 9000
          env:
            - name: APP_ENV
              value: prod
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: symfony-secrets
                  key: app-secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: symfony-secrets
                  key: database-url
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10