
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_php
    environment:
      LOAD_FIXTURES: "true"  # Set to "false" when you don't want to load fixtures
    volumes:
      - ./:/var/www/html
    depends_on:
      database:
        condition: service_healthy
    networks:
      - symfony


  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony


  database:
    image: postgres:15
    container_name: symfony_db
    environment:
      POSTGRES_DB: race-timer
      POSTGRES_USER: stjepan
      POSTGRES_PASSWORD: password
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - symfony
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stjepan -d race-timer" ]
      interval: 5s
      timeout: 5s
      retries: 5



  messenger_worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_messenger_worker
    command: php bin/console messenger:consume async -vv
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
      - database
    networks:
      - symfony



networks:
  symfony:

volumes:
###> doctrine/doctrine-bundle ###
  database-data:
###< doctrine/doctrine-bundle ###
