apiVersion: v1
kind: Secret
metadata:
  name: symfony-secrets
type: Opaque
stringData:
  database-url: "postgresql://stjepan:password@127.0.0.1:5432/race-timer?serverVersion=16&charset=utf8"
  app-secret: "password"