apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: symfony
    component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony
      component: nginx
  template:
    metadata:
      labels:
        app: symfony
        component: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: app-volume
              mountPath: /var/www/html
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: app-volume
          hostPath:
            path: /path/to/your/project  # Update to absolute project path