apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: symfony
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony
      component: database
  template:
    metadata:
      labels:
        app: symfony
        component: database
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: race-timer
            - name: POSTGRES_USER
              value: stjepan
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc