apiVersion: apps/v1
kind: Deployment
metadata:
  name: race-timer-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: race-timer-api
  template:
    metadata:
      labels:
        app: race-timer-api
    spec:
      containers:
        - name: race-timer-api
          image: stjepan11/race-timer-api:latest
          ports:
            - containerPort: 9000
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: symfony-config
                  key: APP_ENV
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: symfony-config
                  key: APP_DEBUG
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: symfony-config
                  key: CORS_ALLOW_ORIGIN
            - name: MESSENGER_TRANSPORT_DSN
              valueFrom:
                configMapKeyRef:
                  name: symfony-config
                  key: MESSENGER_TRANSPORT_DSN
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: symfony-secrets
                  key: database-url
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: symfony-secrets
                  key: app-secret
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
