apiVersion: apps/v1
kind: Deployment
metadata:
  name: race-timer-api-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: race-timer-api-worker
  template:
    metadata:
      labels:
        app: race-timer-api-worker
    spec:
      containers:
      - name: race-timer-api-worker
        image: stjepan11/race-timer-api:latest
        command: ["php", "bin/console", "messenger:consume", "async", "--time-limit=3600"]
        env:
        - name: APP_ENV
          value: prod
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: symfony-secrets
              key: database-url
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: symfony-secrets
              key: app-secret
        - name: MESSENGER_TRANSPORT_DSN
          valueFrom:
            configMapKeyRef:
              name: symfony-config
              key: MESSENGER_TRANSPORT_DSN
